USE [master]
GO
/****** Object:  Database [GroceryStoreDb]    Script Date: 8/29/2021 4:49:43 PM ******/
CREATE DATABASE [GroceryStoreDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'GroceryStoreDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GroceryStoreDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'GroceryStoreDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\GroceryStoreDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [GroceryStoreDb] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [GroceryStoreDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [GroceryStoreDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [GroceryStoreDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [GroceryStoreDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET  ENABLE_BROKER 
GO
ALTER DATABASE [GroceryStoreDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [GroceryStoreDb] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [GroceryStoreDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET RECOVERY FULL 
GO
ALTER DATABASE [GroceryStoreDb] SET  MULTI_USER 
GO
ALTER DATABASE [GroceryStoreDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [GroceryStoreDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [GroceryStoreDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [GroceryStoreDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [GroceryStoreDb] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [GroceryStoreDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [GroceryStoreDb] SET QUERY_STORE = OFF
GO
USE [GroceryStoreDb]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 8/29/2021 4:49:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Customer]    Script Date: 8/29/2021 4:49:44 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Customer](
	[CustomerId] [int] IDENTITY(1,1) NOT NULL,
	[FirstName] [nvarchar](255) NOT NULL,
	[LastName] [nvarchar](255) NOT NULL,
	[ContactNo] [varchar](15) NOT NULL,
	[Email] [nvarchar](255) NOT NULL,
	[Address] [nvarchar](500) NOT NULL,
 CONSTRAINT [PK_Customer] PRIMARY KEY CLUSTERED 
(
	[CustomerId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [GroceryStoreDb] SET  READ_WRITE 
GO
