sonar.projectKey=GroceryStore
sonar.working.directory=D:\\Coding\\GroceryStore\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=D:\\Coding\\GroceryStore
sonar.pullrequest.cache.basepath=D:\\Coding\\GroceryStore
sonar.sources=\
"D:\\Coding\\GroceryStore\\.github\\workflows\\build.yml",\
"D:\\Coding\\GroceryStore\\.vs\\GroceryStoreAPI\\config\\applicationhost.config",\
"D:\\Coding\\GroceryStore\\.vs\\GroceryStoreAPI\\v17\\DocumentLayout.backup.json",\
"D:\\Coding\\GroceryStore\\.vs\\GroceryStoreAPI\\v17\\DocumentLayout.json"

471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.projectKey=GroceryStore:471ACB33-0A48-406A-8735-F9E2ECBA8817
471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.projectName=GroceryStoreAPI
471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.projectBaseDir=D:\\Coding\\GroceryStore\\GroceryStoreAPI
471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.sourceEncoding=utf-8
471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.tests=
471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.sources=\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Controllers\\CustomersController.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Migrations\\20210829102117_initial-create.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Migrations\\20210829102117_initial-create.Designer.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Migrations\\CustomerContextModelSnapshot.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Models\\Customer.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Models\\CustomerContext.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Program.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Startup.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\obj\\Debug\\netcoreapp3.1\\.NETCoreApp,Version=v3.1.AssemblyAttributes.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\obj\\Debug\\netcoreapp3.1\\GroceryStoreAPI.AssemblyInfo.cs",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\appsettings.Development.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\appsettings.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\database.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\Properties\\launchSettings.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\obj\\GroceryStoreAPI.csproj.nuget.dgspec.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\obj\\project.assets.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\bin\\Debug\\netcoreapp3.1\\appsettings.Development.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\bin\\Debug\\netcoreapp3.1\\appsettings.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\bin\\Debug\\netcoreapp3.1\\database.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\bin\\Debug\\netcoreapp3.1\\GroceryStoreAPI.deps.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\bin\\Debug\\netcoreapp3.1\\GroceryStoreAPI.runtimeconfig.dev.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\bin\\Debug\\netcoreapp3.1\\GroceryStoreAPI.runtimeconfig.json",\
"D:\\Coding\\GroceryStore\\GroceryStoreAPI\\obj\\Debug\\netcoreapp3.1\\GroceryStoreAPI.sourcelink.json"

471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.cs.analyzer.projectOutPaths=\
"D:\\Coding\\GroceryStore\\.sonarqube\\out\\0"
471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.cs.roslyn.reportFilePaths=\
"D:\\Coding\\GroceryStore\\.sonarqube\\out\\0\\Issues.json"
471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.cs.scanner.telemetry=\
"D:\\Coding\\GroceryStore\\.sonarqube\\out\\0\\Telemetry.json"

471ACB33-0A48-406A-8735-F9E2ECBA8817.sonar.working.directory=D:\\Coding\\GroceryStore\\.sonarqube\\out\\.sonar\\mod0
161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.projectKey=GroceryStore:161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0
161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.projectName=GTTest
161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.projectBaseDir=D:\\Coding\\GroceryStore\\GTTest
161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.sourceEncoding=utf-8
161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.sources=
161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.tests=\
"D:\\Coding\\GroceryStore\\GTTest\\obj\\GTTest.csproj.nuget.dgspec.json",\
"D:\\Coding\\GroceryStore\\GTTest\\obj\\project.assets.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\appsettings.Development.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\appsettings.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\database.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\GroceryStoreAPI.deps.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\GroceryStoreAPI.runtimeconfig.dev.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\GroceryStoreAPI.runtimeconfig.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\GTTest.deps.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\GTTest.runtimeconfig.dev.json",\
"D:\\Coding\\GroceryStore\\GTTest\\bin\\Debug\\netcoreapp3.1\\GTTest.runtimeconfig.json",\
"D:\\Coding\\GroceryStore\\GTTest\\obj\\Debug\\netcoreapp3.1\\GTTest.sourcelink.json",\
"D:\\Coding\\GroceryStore\\GTTest\\CustomersControllerTests.cs"

161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.cs.analyzer.projectOutPaths=\
"D:\\Coding\\GroceryStore\\.sonarqube\\out\\1"
161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.cs.roslyn.reportFilePaths=\
"D:\\Coding\\GroceryStore\\.sonarqube\\out\\1\\Issues.json"
161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.cs.scanner.telemetry=\
"D:\\Coding\\GroceryStore\\.sonarqube\\out\\1\\Telemetry.json"

161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0.sonar.working.directory=D:\\Coding\\GroceryStore\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.cs.opencover.reportsPaths=coverage.xml
sonar.exclusions=coverage.xml
sonar.visualstudio.enable=false

sonar.modules=471ACB33-0A48-406A-8735-F9E2ECBA8817,161BFCB3-66F2-49EE-8D4A-A3D9194A4BB0

